//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Краснов_экзамен
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Midlname { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual places places { get; set; }
    }
}
